### PR TITLE
added backward compatibility to flutter 2

### PR DESCRIPTION
**Pull request by arjundevlucid**
❤️ OpenSource

### CODE REVIEW

**Comment by Shreemanarjun** [comment]
Please merge @iampawan  👍.Fixed #145

**Comment by Shreemanarjun** [comment]
I resolved conflicts.  Please merge @iampawan .

**Comment by iampawan** [comment]
Will check and merge

**Comment by abehbatre** [comment]
LGTM

**Comment by the-kool-sk** [comment]
when this will be released?

**Review by RealSollyM — CHANGES_REQUESTED** [review]
Vx updates and Example updates should be PR separately since the example is not implementing the Vx updates in this PR.

**Comment by iampawan** [comment]
+1 to @RealSollyM . @Shreemanarjun

**Pull request closed without merging**
